import { useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home = () => {
  const [name, setName] = useState('test');
  const router = useRouter();
  console.log(router);

  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Link to ’ factory Page</h2>
        <Link href="/factory/factoryList">Move to home</Link>
        <Link href="/factory/factoryList${}">Move to /factory</Link>

        <button
          type="button"
          className="btn"
          onClick={() => router.push('/factory/factoryList')}
        >
          factory
        </button>
        <input
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <button
          type="button"
          className="btn"
          onClick={() => router.push(`/factory/${name}`)}
        >{name} 으로 가기</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  );
};

export default Home;
